<?php get_header(); ?>

<div class="page-banner">
    <?php
    $header_background_image_id = get_theme_mod('header_background_image');
    if ($header_background_image_id) {
        $header_background_image_url = wp_get_attachment_url($header_background_image_id);
        echo '<div class="page-banner__bg-image" style="background-image: url(' . esc_url($header_background_image_url) . ');">';
        echo '</div>';
    } else {
        echo '<div class="page-banner__bg-image" style="background-image: url(' . content_url("/uploads/2023/02/Groepsfoto-scaled.jpg") . ')"></div>';
    }

    ?>

    <div class="page-banner__content container t-center c-white">

        <h1 class="headline headline--large">Welkom!</h1>
        <br>
        <br>
        <h2 class="headline headline--medium">bij SKV De Narre Knollen</h2>
        <h3 class="headline headline--small">soest</h3>
        <br>
        <br>
    </div>
</div>
<div class="news-container" style="display: none;">
    <h2 class="headline headline--small-plus t-center">Nieuws</h2>
    <div class="all-news">
        <?php
        $today = date('Ymd');
        $homepageNews = new WP_Query(
            [
                'posts_per_page' => 2,
                'post_type' => 'nieuws',
                'meta_key' => 'news_date',
                'orderby' => 'meta_value_num',
                'order' => 'ASC',
                'meta_query' => [
                    [
                        'key' => 'news_date',
                        'compare' => '>=',
                        'value' => $today,
                        'type' => 'numeric'
                    ]

                ]
            ]);
        while ($homepageNews->have_posts()) {
            $homepageNews->the_post();
            get_template_part('template-parts/content', 'news');
        }
        ?>
    </div>
    <p class="t-center no-margin"><a href="nieuws" class="btn btn--yellow">Nieuws overzicht</a></p>
</div>

<div class="container prins-container">
    <div class="d-flex justify-content-center flex-column ">
        <div class="d-flex">
            <h1>Prins Rene I</h1>
            <h1>Hofdame Irene</h1>
        </div>
        <img style="height: 100%;" src="<?= content_url("/uploads/2024/11/IMG_7568b-scaled.jpg") ?>"
             alt="Wie wordt de 50ste hoogheid van de Narre Kollen?">
    </div>
</div>

<div class="event-container container">
    <h2 class="headline headline--small-plus t-center">Agenda</h2>
    <div class="all-events">


        <?php
        $homepageEvents = new WP_Query(
            [
                'posts_per_page' => 4,
                'post_type' => 'agenda',
                'meta_key' => 'event_date',
                'orderby' => 'meta_value_num',
                'order' => 'ASC',
                'meta_query' => [
                    [
                        'key' => 'event_date',
                        'compare' => '>=',
                        'value' => $today,
                        'type' => 'numeric'
                    ]

                ]
            ]);

        while ($homepageEvents->have_posts()) {
            $homepageEvents->the_post();
            get_template_part('template-parts/content', 'event');
        }
        ?>
        <p class="t-center no-margin"><a href="agenda" class="btn btn--blue">Jaar agenda</a></p>
    </div>
</div>
<div class="container hero-slider" data-slide-count="<?php echo get_theme_mod('slider_count_setting', 3); ?>">
    <div data-glide-el="track" class="glide__track">
        <div class="glide__slides">
            <!-- Your slides will be dynamically generated by the JavaScript code -->
            <?php
            for ($i = 1; $i <= get_theme_mod('slider_count_setting', 3); $i++) {
                echo '<div class="hero-slider__slide">';
                echo '<img src="' . get_theme_mod('slider_image_' . $i) . '" alt="slide' . $i . '">';
                echo '</div>';
            }
            ?>
        </div>
        <div class="slider__bullets glide__bullets" data-glide-el="controls[nav]"></div>
    </div>
</div>

<?php get_footer();

?>
